### PR TITLE
Feature/utilities

### PR DESCRIPTION
**Pull request by ReeceJordaan**
Updated Utility unit tests to use new constructors.

### CODE REVIEW

**Comment by jacqu3sk** [comment]
It seems like there is many test that are not passing. There is also one test causing a segmentation fault. I just want to know if its intentional

**Comment by ReeceJordaan** [comment]
Thanks Jacques, i've fixed them. Just confirm that they are working on your side?

**Comment by jacqu3sk** [comment]
All the tests pass 👍

**Review by jacqu3sk — APPROVED** [review]
All good

**Review by RKruse42 — APPROVED** [review]

**Pull request merged**
