### PR TITLE
Version 1.0

### PR DESCRIPTION
**Pull request by jacqu3sk**

### CODE REVIEW

**Comment by CartographySilence** [comment]
I aint approving

**Review by CartographySilence — APPROVED** [review]
Ermmm yeah good job but i think we need a tech tree actually so this version sucks

**Review by 0ptim0s — APPROVED** [review]

**Review by RKruse42 — APPROVED** [review]

**Comment by ReeceJordaan** [comment]
I'll consider it

**Comment by 0ptim0s** [comment]
The project looks amazing

**Pull request merged**
