### PR TITLE
Hotfix/iterator fix

### PR DESCRIPTION
**Pull request by 0ptim0s**
Fixed the iterators and handled memory leaks

### CODE REVIEW

**Review by jacqu3sk — APPROVED** [review]
yea it is much better

**Review by ReeceJordaan — CHANGES_REQUESTED** [review]
This is definitely an improvement but there are still a few areas where memory is leaked such as in ResidentialBuildingIteratorTest:

`row1.push_back(new House());
    row1.push_back(new Apartment());
    row2.push_back(NULL);
    row2.push_back(new House());`
    
    Should be changed to:
    
    `row1.push_back(h);
    row1.push_back(a);
    row2.push_back(NULL);
    row2.push_back(h);`

**Comment by 0ptim0s** [comment]
Thanks i corrected that memory leak

**Review by RKruse42 — APPROVED** [review]
It's a lot better - it does not look like the other memory leaks are from Iterator

**Review by ReeceJordaan — APPROVED** [review]
I managed to find the rest of the leaks and fixed them. There are no more leaks now and all tests pass. This can be merged now.

**Pull request merged**
